CASES = (
    "Dr. Smith bought 5 kg.",
    "Hello ...s world",
    'Hello [Bonjour]{lang="fr"}.',
    "They changed out their clothes (stained with blood).",
    "The backup battery (still warm from the morning test) sat beside the console.",
    "One sentence. Two sentences.\n\nSecond paragraph.",
    "Hello ...c world",
    "One. @mark Two.",
    '[GIF]{ph="dʒɪf"} is a short word.',
    'She said, "Hello." Then left.',
    "Café déjà vu. Привет мир.",
    "Wait (really), what?",
    "",
)
